import ExcelJS from "exceljs";
import fs from "node:fs/promises";
import path from "node:path";

const root=process.cwd();
const parse=async file=>{const text=await fs.readFile(file,"utf8");const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=false;else cell+=c;}else if(c==='"')quoted=true;else if(c===','){row.push(cell);cell="";}else if(c==='\n'){row.push(cell);rows.push(row);row=[];cell="";}else if(c!=='\r')cell+=c;}return rows;};
const workbook=new ExcelJS.Workbook();workbook.creator="Localogue Community Data";workbook.title="Localogue Community Data 浏览工作簿";
const genreRowsForSummary=await parse(path.join(root,"exports","csv","genre-overview.csv"));
const facetNames={theme:"主题",role:"角色",wardrobe:"服装",body:"体型与外观",act:"行为",practice:"玩法与偏好",production:"制作类别",media:"媒介与格式",rating:"分级"};
const facetCounts=new Map();for(const row of genreRowsForSummary.slice(1))facetCounts.set(row[1],(facetCounts.get(row[1])??0)+1);
const summary=workbook.addWorksheet("分类统计",{views:[{state:"frozen",ySplit:4}]});summary.mergeCells("A1:F1");summary.getCell("A1").value="Localogue 三语分类词表 · V0.3.1";summary.getCell("A1").font={bold:true,size:18,color:{argb:"FFFFFFFF"}};summary.getCell("A1").fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF173F5F"}};summary.getCell("A1").alignment={vertical:"middle"};summary.getRow(1).height=34;summary.mergeCells("A3:F3");summary.getCell("A3").value="日文为规范名；简体中文与英文用于显示和检索。词条按九个语义分面管理，别名不会获得新的 ID。";summary.getCell("A3").fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFEAF2F8"}};summary.getCell("A3").alignment={vertical:"middle",wrapText:true};summary.getRow(3).height=32;summary.addRow([]);summary.addRow(["facet","中文分面","条目数"]);for(const [facet,count] of facetCounts)summary.addRow([facet,facetNames[facet],count]);const summaryHeader=summary.getRow(5);summaryHeader.font={bold:true,color:{argb:"FFFFFFFF"}};summaryHeader.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF315B7D"}};summary.autoFilter={from:"A5",to:`C${summary.rowCount}`};summary.columns=[{width:18},{width:24},{width:12},{width:16},{width:16},{width:16}];
for(const [sheetName,file] of [["女优总览","actress-overview.csv"],["作品总览","work-overview.csv"],["分类词表","genre-overview.csv"],["分类别名","genre-aliases.csv"]]){const rows=await parse(path.join(root,"exports","csv",file));const sheet=workbook.addWorksheet(sheetName,{views:[{state:"frozen",ySplit:1}]});sheet.addRows(rows);sheet.autoFilter={from:{row:1,column:1},to:{row:Math.max(1,sheet.rowCount),column:sheet.columnCount}};const header=sheet.getRow(1);header.font={bold:true,color:{argb:"FFFFFFFF"}};header.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF315B7D"}};header.alignment={vertical:"middle",horizontal:"center",wrapText:true};header.height=26;sheet.eachRow((row,index)=>{if(index>1&&index%2===0)row.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFF3F7FA"}};row.alignment={vertical:"top",wrapText:true};});sheet.columns.forEach((column,index)=>{let max=12;column.eachCell({includeEmpty:false},cell=>max=Math.max(max,String(cell.value??"").length+2));column.width=Math.min(index===19?48:max,40);});}
await fs.mkdir(path.join(root,"exports","xlsx"),{recursive:true});await workbook.xlsx.writeFile(path.join(root,"exports","xlsx","localogue-community-data.xlsx"));console.log("已生成 exports/xlsx/localogue-community-data.xlsx");
